"""
MIB から得たスキーマ（JSON）を受け取り、ハンドラ骨格（Pythonモジュール）を生成する簡易ジェネレータ。

使い方例:
  python generator.py schema.json outdir/
"""
import sys
import os
import json

HANDLER_TMPL = '''"""Generated handler skeleton for {name}

This module provides:
- init_table() to ensure DDL exists
- get_{name}(oid=None)
- set_{name}(oid_or_index, value)
- next_oid(current_oid) : simple next-row support for GETNEXT
"""

from ..persistence import SQLiteAdapter
import datetime

DB_PATH = 'data/db.sqlite'

# Optional OID base (dotted string) if known; used to map OIDs to index columns
OID_BASE = {oid_base}

# Columns that should be integers (auto-generated)
INTEGER_COLS = {integer_cols}

def _ensure_db():
    global db
    try:
        db
    except NameError:
        db = SQLiteAdapter(DB_PATH)

# simple validator based on SQL column types generated by the framework
def _validate_data(data, columns):
    """Validate dict 'data' against columns mapping like {'col': {'type': 'INTEGER'|'TEXT', ...}}.
    Returns (True, None) on success or (False, error_message) on failure.
    Supports optional constraints: max_length for TEXT, min/max for INTEGER.
    """
    for k, v in (data or {}).items():
        col_meta = columns.get(k)
        if not col_meta:
            # unknown column: accept (generator controls schema) or reject
            continue
        # allow older simple string mapping
        if isinstance(col_meta, str):
            t = col_meta.upper()
            meta = {}
        else:
            t = col_meta.get('type', '').upper()
            meta = dict(col_meta)
        if 'INTEGER' in t:
            try:
                iv = int(v)
            except Exception:
                return False, f"column {k} expects integer"
            if 'min' in meta and iv < meta['min']:
                return False, f"column {k} min is {meta['min']}"
            if 'max' in meta and iv > meta['max']:
                return False, f"column {k} max is {meta['max']}"
        elif 'TEXT' in t:
            try:
                s = str(v)
            except Exception:
                return False, f"column {k} expects text"
            if 'max_length' in meta and len(s) > meta['max_length']:
                return False, f"column {k} max_length is {meta['max_length']}"
        # extend with other SNMP-specific validations as needed
    return True, None


# ensure table exists when module imported
try:
    _ensure_db()
    db.create_table_for_object('{name}', {columns}, unique_cols={unique_cols})
except Exception:
    pass


def init_table():
    _ensure_db()
    db.create_table_for_object('{name}', {columns}, unique_cols={unique_cols})


def _parse_oid(oid):
    """Normalize OID input to list of string components"""
    if oid is None:
        return []
    if isinstance(oid, str):
        parts = [p for p in oid.strip().split('.') if p != '']
        return parts
    if isinstance(oid, (list, tuple)):
        return [str(p) for p in oid]
    return []


def _oid_to_index_map(oid):
    """If OID_BASE and unique_cols are set, map trailing OID components to unique columns.
    Returns dict of {col: value} or None if mapping not possible.
    """
    parts = _parse_oid(oid)
    if not parts:
        return None
    if OID_BASE:
        base = str(OID_BASE).split('.') if isinstance(OID_BASE, str) else []
        if len(parts) <= len(base):
            return None
        if parts[:len(base)] != base:
            return None
        suffix = parts[len(base):]
    else:
        # no base known: use entire OID as suffix
        suffix = parts

    # if unique_cols provided, attempt to map last N suffix components to them
    if {unique_cols} and {unique_cols} != 'None':
        ucols = {unique_cols}
        if len(suffix) < len(ucols):
            return None
        vals = suffix[-len(ucols):]
        res = {}
        for k, v in zip(ucols, vals):
            try:
                res[k] = int(v)
            except Exception:
                res[k] = v
        return res
    # fallback: treat last component as id
    try:
        return {'id': int(suffix[-1])}
    except Exception:
        return None


def _validate_row(row):
    """Validate and coerce row dict based on INTEGER_COLS. Raises ValueError on bad types."""
    if not isinstance(row, dict):
        raise ValueError('row must be a dict')
    for k in INTEGER_COLS or []:
        if k in row and row[k] is not None:
            try:
                row[k] = int(row[k])
            except Exception:
                raise ValueError(f'invalid integer for column {k}: {row[k]}')
    return row


def get_{name}(oid=None, ctx=None):
    """Return value by oid/index or latest for scalars"""
    _ensure_db()
    if oid is None:
        rows = db.query_all('{name}')
        if not rows:
            return None
        return rows[-1].get('value') if 'value' in rows[-1] else rows[-1]

    # If unique index columns exist, try mapping from OID to index values
    idx_map = _oid_to_index_map(oid)
    if idx_map:
        # build WHERE clause from idx_map
        keys = list(idx_map.keys())
        where = ' AND '.join([f'"{k}"=?' for k in keys])
        params = tuple(idx_map[k] for k in keys)
        cur = db.execute(f'SELECT * FROM "{name}" WHERE {where}', params)
        r = cur.fetchone()
        return dict(r) if r else None

    # fallback: assume numeric id
    try:
        cur = db.execute('SELECT * FROM "{name}" WHERE id=?', (int(oid),))
    except Exception:
        cur = db.execute('SELECT * FROM "{name}" WHERE id=?', (int(oid),))
    r = cur.fetchone()
    return dict(r) if r else None


def set_{name}(oid, value, ctx=None):
    """Insert or update. For scalars, oid may be ignored."""
    _ensure_db()
    now = datetime.datetime.utcnow().isoformat() + 'Z'
    # pre-validate input
    cols = {columns}
    if {is_scalar}:
        # scalar: coerce to string and store
        db.upsert('{name}', {{'value': str(value), 'updated_at': now}}, unique_cols={unique_cols})
        return True
    else:
        # tables: expect dict or simple value
        # Support batch updates: list of row dicts -> atomic bulk upsert
        if isinstance(value, list):
            try:
                # validate rows
                validated = []
                for r in value:
                    validated.append(_validate_row(r))
                db.bulk_upsert('{name}', validated, unique_cols={unique_cols})
                return True
            except Exception:
                return False
        if isinstance(value, dict):
            # coerce/validate integer columns first
            try:
                value = _validate_row(value)
            except ValueError:
                return False
            # run column-type validation
            ok, err = _validate_data(value, cols)
            if not ok:
                return False
            # persist atomically within a transaction
            try:
                with db.transaction():
                    db.upsert('{name}', value, unique_cols={unique_cols})
                return True
            except Exception:
                return False
        else:
            # set single column 'value' if present
            try:
                db.upsert('{name}', {{'value': str(value), 'updated_at': now}}, unique_cols={unique_cols})
                return True
            except Exception:
                return False


def next_oid_{name}(current_oid=None):
    """Return next row id after current_oid. If current_oid is None, return first id."""
    _ensure_db()
    rows = db.query_all('{name}')
    if not rows:
        return None
    # sort by id if present
    if 'id' in rows[0]:
        ids = [r['id'] for r in rows]
        ids.sort()
        if current_oid is None:
            return ids[0]
        try:
            cur = int(current_oid)
        except Exception:
            return ids[0]
        for i in ids:
            if i > cur:
                return i
        return None
    else:
        # fallback: return None
        return None
'''



def _snmp_type_to_sql(snmp_type):
    t = (snmp_type or '').lower()
    # integer-like types
    if 'counter64' in t or 'integer' in t or 'int' in t or 'unsigned' in t:
        return 'INTEGER'
    # text / octet types
    if 'octet' in t or 'string' in t or 'oid' in t:
        return 'TEXT'
    # counters / gauges are numeric
    if 'counter' in t or 'timeticks' in t or 'gauge' in t:
        return 'INTEGER'
    return 'TEXT'


def _parse_snmp_syntax(snmp_syntax):
    """Extract base type and simple constraints from an SNMP SYNTAX string.

    Returns (base_type_str, constraints_dict). Examples handled:
      'OCTET STRING (SIZE (0..64))' -> ('OCTET STRING', {'max_length': 64})
      'INTEGER (0..255)' -> ('INTEGER', {'min':0, 'max':255})
    This is heuristic and supports common pysmi-style strings.
    """
    if not snmp_syntax:
        return None, {}
    s = str(snmp_syntax)
    # try to capture SIZE(n) or SIZE(m..n)
    import re
    constraints = {}
    m = re.search(r'SIZE\s*\(\s*(\d+)(?:\.\.(\d+))?\s*\)', s, re.IGNORECASE)
    if m:
        # if range, use upper bound as max_length; else use single value
        if m.group(2):
            constraints['max_length'] = int(m.group(2))
        else:
            constraints['max_length'] = int(m.group(1))
    # INTEGER range like (min..max)
    m2 = re.search(r'INTEGER\s*\(\s*(-?\d+)\s*\.\.\s*(-?\d+)\s*\)', s, re.IGNORECASE)
    if m2:
        constraints['min'] = int(m2.group(1))
        constraints['max'] = int(m2.group(2))
    # fallback: try to capture a parenthesized range for generic types
    m3 = re.search(r'\(\s*(-?\d+)\s*\.\.\s*(-?\d+)\s*\)', s)
    if m3 and 'min' not in constraints:
        try:
            constraints['min'] = int(m3.group(1))
            constraints['max'] = int(m3.group(2))
        except Exception:
            pass
    # base type: strip trailing constraint parentheses
    base = re.sub(r'\(.*\)', '', s).strip()
    return base, constraints


def generate_handlers(schema_path, outdir):
    with open(schema_path, 'r', encoding='utf-8') as f:
        schema = json.load(f)
    os.makedirs(outdir, exist_ok=True)
    mib = os.path.splitext(os.path.basename(schema_path))[0]

    # Helper: find entry definition by name
    entries = {o.get('name'): o for o in schema.get('objects', []) if o.get('kind') in ('entry','table','scalar','column')}

    for obj in schema.get('objects', []):
        name = obj.get('name', 'unknown')
        # sanitize name to be filename-friendly
        safe_name = ''.join(c if c.isalnum() or c=='_' else '_' for c in name)
        is_scalar = (obj.get('kind') == 'scalar')
        columns = {}
        unique_cols = None
        if obj.get('kind') == 'table' and obj.get('entry_type'):
           entry = entries.get(obj.get('entry_type'))
           if entry and entry.get('fields'):
               for f in entry.get('fields'):
                   col_name = f.get('name')
                   syntax = f.get('type')
                   base, constraints = _parse_snmp_syntax(syntax)
                   sql_type = _snmp_type_to_sql(base or syntax)
                   if constraints:
                       meta = {'type': sql_type}
                       meta.update(constraints)
                       columns[col_name] = meta
                   else:
                       columns[col_name] = sql_type
               # ensure id primary key
               columns = {'id': 'INTEGER PRIMARY KEY AUTOINCREMENT', **columns}
               # Heuristic: collect any field whose name suggests an index (contains 'Index' or endswith 'index')
               index_fields = []
               for f in entry.get('fields') or []:
                   fname = f.get('name')
                   if not fname:
                       continue
                   if 'Index' in fname or fname.lower().endswith('index') or 'index' == fname.lower():
                       index_fields.append(fname)
               if index_fields:
                   unique_cols = index_fields
           else:
               # generic table
               columns = {'id': 'INTEGER PRIMARY KEY AUTOINCREMENT', 'value': 'TEXT', 'updated_at': 'TEXT'}
        elif obj.get('kind') == 'entry' and obj.get('fields'):
            # entry as standalone table
            cols = {}
            for f in obj.get('fields'):
                syntax = f.get('type')
                base, constraints = _parse_snmp_syntax(syntax)
                sql_type = _snmp_type_to_sql(base or syntax)
                if constraints:
                    meta = {'type': sql_type}
                    meta.update(constraints)
                    cols[f.get('name')] = meta
                else:
                    cols[f.get('name')] = sql_type
            columns = {'id': 'INTEGER PRIMARY KEY AUTOINCREMENT', **cols}
            is_scalar = False
            # heuristic for unique_cols for entries
            first_field = obj.get('fields')[0].get('name') if obj.get('fields') else None
            if first_field and ('Index' in first_field or first_field.lower().endswith('index')):
                unique_cols = [first_field]
        else:
            # scalar or unknown -> single-value table
            columns = {'value': 'TEXT', 'updated_at': 'TEXT'}
            is_scalar = True

        # Render Python literal for columns mapping; support dict values for metadata
        cols_items = []
        for k, v in columns.items():
            if isinstance(v, str):
                cols_items.append(f"'{k}': '{v}'")
            else:
                cols_items.append(f"'{k}': {repr(v)}")
        cols_literal = '{' + ', '.join(cols_items) + '}'
        # integer columns for validation
        integer_cols = [k for k, v in columns.items() if 'INT' in v.upper()]
        if integer_cols:
            integer_literal = '[' + ', '.join(f"'{c}'" for c in integer_cols) + ']'
        else:
            integer_literal = '[]'
        if unique_cols:
            unique_literal = '[' + ', '.join(f"'{c}'" for c in unique_cols) + ']'
        else:
            unique_literal = 'None'

        fname = os.path.join(outdir, f'{safe_name}.py')
        with open(fname, 'w', encoding='utf-8') as fh:
            # Use simple literal replacements to avoid str.format parsing embedded dict braces
            out = HANDLER_TMPL
            out = out.replace('{name}', safe_name)
            out = out.replace('{columns}', cols_literal)
            out = out.replace('{is_scalar}', str(is_scalar))
            out = out.replace('{unique_cols}', unique_literal)
            out = out.replace('{oid_base}', 'None')
            out = out.replace('{integer_cols}', integer_literal)
            fh.write(out)

    # If no objects, create a placeholder
    if not schema.get('objects'):
        with open(os.path.join(outdir, f'{mib}_placeholder.py'), 'w', encoding='utf-8') as fh:
            out = HANDLER_TMPL
            out = out.replace('{name}', 'placeholder')
            out = out.replace('{columns}', "{'value':'TEXT','updated_at':'TEXT'}")
            out = out.replace('{is_scalar}', 'True')
            out = out.replace('{unique_cols}', 'None')
            out = out.replace('{oid_base}', 'None')
            out = out.replace('{integer_cols}', '[]')
            fh.write(out)


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('Usage: python generator.py schema.json outdir', file=sys.stderr)
        sys.exit(2)
    generate_handlers(sys.argv[1], sys.argv[2])
